#!/bin/bash

decay=1e-4
lr=0.001
layer=3
seed=2020
dataset="lastfm"
topks="[10,20]"
recdim=128
use_drop_edge=0
keepprob=1.0
batch_size=1024
dropout_i=0.6
dropout_u=0.2
dropout_n=0.6
neighbor_k=20
item_semantic_emb_file='../data/lastfm/lastfm_embeddings_simcse_kg.pt'
user_semantic_emb_file='../data/lastfm/lastfm_embeddings_simcse_kg_user.pt'
epochs=1000
eval_freq=5
checkpoint_tag='k20_cfprior04_lcl006_sccf001_ema995s400_seed2020'
comment='k20_cfprior04_lcl006_sccf001_ema995s400_seed2020'

CUDA_VISIBLE_DEVICES=0 python -u main.py \
  --bpr_batch=$batch_size \
  --decay=$decay \
  --lr=$lr \
  --layer=$layer \
  --seed=$seed \
  --dataset="$dataset" \
  --topks="$topks" \
  --recdim=$recdim \
  --use_drop_edge=$use_drop_edge \
  --keepprob=$keepprob \
  --neighbor_k=$neighbor_k \
  --dropout_i=$dropout_i \
  --dropout_u=$dropout_u \
  --dropout_n=$dropout_n \
  --item_semantic_emb_file="$item_semantic_emb_file" \
  --user_semantic_emb_file="$user_semantic_emb_file" \
  --epochs=$epochs \
  --eval_freq=$eval_freq \
  --tensorboard=0 \
  --load=0 \
  --checkpoint_tag="$checkpoint_tag" \
  --comment="$comment" \
  --use_neighbor_cf_prior=1 \
  --neighbor_cf_alpha=0.4 \
  --layer_cl_reg=0.006 \
  --layer_cl_temp=0.2 \
  --sccf_reg=0.001 \
  --sccf_temp=0.2 \
  --use_ema=1 \
  --ema_decay=0.995 \
  --ema_start_epoch=400 \
  --neg_k=1 \
  --multi_neg_loss=0 \
  --use_item_graph_prop=0 \
  --use_itemknn_score=0 \
  --use_social_graph=0 \
  --use_semantic_gate=0 \
  --use_layer_weight=0 \
  --use_item_bias=0 \
  --semantic_cl_reg=0
